const cron = require('node-cron');
const { v4: uuidv4 } = require('uuid');
const { getDb } = require('../models/database');
const { generatePost } = require('./ai');
const { agents } = require('../data/agents');

const AGENT_CATEGORIES = {
  'sheikh-ul-hadith': ['حدیث'],
  'mufti-sahib': ['فتاویٰ'],
  'waiz-sahib': ['واقعات', 'نصیحت', 'اقوال'],
  'aalima-sahiba': ['خواتین'],
  'mufassir-sahib': ['تفسیر']
};

async function generateAndSavePost() {
  const db = getDb();
  const agentList = agents.filter(a => AGENT_CATEGORIES[a.id]);
  const randomAgent = agentList[Math.floor(Math.random() * agentList.length)];
  const categories = AGENT_CATEGORIES[randomAgent.id];
  const randomCategory = categories[Math.floor(Math.random() * categories.length)];

  try {
    const post = await generatePost(randomCategory, randomAgent.id);
    db.prepare(`
      INSERT INTO posts (id, agent_id, category, title, content, source_reference)
      VALUES (?, ?, ?, ?, ?, ?)
    `).run(
      uuidv4(),
      post.agent_id,
      post.category,
      post.title,
      post.content,
      post.source_reference
    );
    console.log(`New post generated by ${randomAgent.name}: ${post.title}`);
  } catch (error) {
    console.error('Failed to generate post:', error.message);
  }
}

function startContentScheduler() {
  // Generate a new post every 30 minutes
  cron.schedule('*/30 * * * *', () => {
    generateAndSavePost();
  });

  // Generate initial post after 10 seconds
  setTimeout(() => {
    generateAndSavePost();
  }, 10000);

  console.log('Content scheduler initialized - generating posts every 30 minutes');
}

module.exports = { startContentScheduler, generateAndSavePost };
